channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - fbpca
  - faiss-cpu=1.8.0
  - scikit-image=0.24.0
  - cython=3.0
  - umap-learn=0.5.7
  - numpy=1.26.4
  - hdf5storage
  - pandas
  - numba=0.60.0
  - matplotlib
  - fftw=3.3
  - ffmpeg=4.2
  - numpy=1.26
  # - pandas
  # - pywavelets
  # - numpy #=1.23
  # - matplotlib
  # - numba
