channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy #=1.23
  # - faiss-cpu=1.6.5
  - matplotlib
  - seaborn
  - hdf5storage
  - umap-learn
  - numba
  - scikit-image #=0.19
  # - cython=3.0
  # - fftw=3.3
  - pandas
  - fbpca
  - ffmpeg #=4.2
  - opentsne
