site_name: neuroposelib
repo_url: https://github.com/joshuahwu/neuroposelib

theme:
  name: 'material'
  palette:
    primary: 'gray'
    features:
      - navigation.tabs
plugins:
    - search                           # make sure the search plugin is enabled
    - mkdocstrings:                    # plugin for generating documentation from Python docstrings
        handlers:                      # handler is responsible for loading and parsing source files
          python:                      # set handler is for Python
            options:                   # configuration of options for the Python handler
              docstring_style: numpy   # style of docstrings (convention followed)
              show_source: true        # include a link to the source code
              show_members: source     # configures the order in which members (methods, attributes, etc.) are displayed.
              docstring_section_style: list # If set to 'source', it means the order in the source code will be maintained.
    - gen-files:
        scripts:
            - docs/gen_ref_pages.py     # script for generating reference pages
    - literate-nav:
          nav_file: docs/SUMMARY.md     # navigation file for literate navigation

    # - macros:
    #     include_yaml: 
    #       - docs/extra.yaml
    - section-index                    # plugin for creating section index
    # - gallery:
    #     examples_dirs: docs/examples          # path to your example scripts
    #     gallery_dirs: docs/generated/gallery  # where to save generated gallery
nav:
    - Home: index.md
    - API References: reference/
    # - Tutorials: generated/gallery
    # - Workflow: notes/00-workflow.md
    # - Structure: notes/01-structure.md
    # - Packaging: notes/02-packaging.md
    # - Documentation: notes/03-documentation.md
    # - Docstrings: notes/04-docstrings.md
    # - Linters and Tests: notes/05-linters-and-tests.md
    # - CI: notes/06-ci.md
    # - Data: notes/07-data.md
    # - Open Source: notes/08-open-source.md
    # - About: about.md


# extra:
#   pose: "Array of 3D pose values of shape (# frames, # keypoints, 3 coordinates)." 
#   ids: "Id label for each frame in pose, e.g. video id (# frames)."
#   meta: "Id label for each frame in pose, e.g. video id (# frames)."
#   meta_by_frame: "Metadata for each frame (# frames, # metadata)."
#   connectivity: "Connectivity object containing keypoint/joint/skeletal information."
#   features: "2D array of features (# frames, # features)."
#   path: Path to file.
#   dtype: "Desired data type of output array."
#   feat_labels: "Labels for features in columns of features array."